### ISSUE TITLE
Invalid floorplan for several OpenROAD designs

### ISSUE THREAD

**Issue by tajayi** [abk-openroad/TritonMacroPlace#1]
**Priority:** High

I have observed several bad placement of macros in the OpenROAD flow.

**overlapping macro placement**
bp_fe_top_tsmc65lp
![image](https://user-images.githubusercontent.com/1457793/62891191-13756600-bd13-11e9-9a2c-1fa3962df8dc.png)

**macro placement outside the core boxe**
swerv_wrapper_tsmc65lp
![image](https://user-images.githubusercontent.com/1457793/62891282-4f103000-bd13-11e9-84d4-ba24e398248b.png)

**maro sideways rotation** (causes issues with power grid)
tinyRocket_tsmc65lp
![image](https://user-images.githubusercontent.com/1457793/62891650-42400c00-bd14-11e9-8d9d-0960079be86f.png)

**Steps to Reproduce:**
1. Setup the latest version of the flow (commit e7abe2a8a010019f5a0c74472b96842cb66c2a71)
2. Setup the tsmc65lp platform
3. Attempt `make floorplan` on any of the designs listed above

**Comment by mgwoo** [comment]
The problem in tinyRocket_tsmc65lp and bp_fe_top_tsmc65lp is solved by the following commit:
https://github.com/The-OpenROAD-Project/TritonMacroPlace/commit/f13ebbbf8f91d5f41f1d20d6bc780d632345a938
