### ISSUE TITLE
file INSTALL cannot find: "...TritonMacroPlace/src/plot.h".

### ISSUE THREAD

**Issue by speedbooster** [abk-openroad/TritonMacroPlace#2]
**make install** gives:

> [ 30%] Built target LefBisonTarget
> [ 37%] Built target lef
> [ 38%] Built target lefzlib
> [ 44%] Built target clef
> [ 44%] Built target clefzlib
> [ 89%] Built target OpenSTA
> [ 89%] Built target sta
> [ 95%] Built target ABKCommon
> [ 97%] Built target fplan
> [100%] Built target fplanlib
> Install the project...
> -- Install configuration: ""
> -- Installing: /usr/local/include/lefdefIO.h
> -- Installing: /usr/local/include/parse.h
> CMake Error at cmake_install.cmake:41 (file):
>   file INSTALL cannot find
>   "/home/user/Downloads/openflow/TritonMacroPlace/src/plot.h".
> 
> 
> make: *** [Makefile:86: install] Error 1
>

**Comment by mgwoo** [comment]
Thanks for letting me know. 
I think these header files should be private, so no need to be installed. 
The public header would be implemented soon.

**Comment by speedbooster** [comment]
Meanwhile.......? Is this tool usable?
