### ISSUE TITLE
Empty line in IP config file

### ISSUE THREAD

**Issue by gadfort** [abk-openroad/TritonMacroPlace#7]
During parsing of the configuration file, if it encounters an empty line, it fails and exits out. 

The better behavior would be to skip that line just like it does for the comments, like comments empty lines can help with file readability.

One possible solution would be:
https://github.com/The-OpenROAD-Project/TritonMacroPlace/blob/9f5f77d5dbeab4784237f39ccc1af7c8fb92fd4e/src/circuit.cpp#L1232

A simple fix would be to look at the length of the `buf1` and skip processing if it is `0`.

Thanks,
Peter

**Comment by mgwoo** [comment]
Thanks for suggestion, but the IP_config.cfg would be removed in the near future. 
The other vars like FIN, PITCH, ... are not used at all in TritonMP.
The Tcl flag with "-halo_x" and "-halo_y" would be added in the Tcl command.

**Comment by gadfort** [comment]
Okay, thanks. I'd consider this resolved then if the tcl interface is coming.
